FROM node:22
## 设置 locale 和时区
#RUN apk add --no-cache tzdata \
#    && cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
#    && echo "ja_JP.UTF-8 UTF-8" > /etc/locale.gen \
#    && localedef -i ja_JP -f UTF-8 ja_JP.UTF-8

WORKDIR /usr/src/app

# 全局安装 create-next-app
# RUN npm install -g create-next-app

# 启动 Next.js 的开发服务器
#CMD ["npm", "run", "dev"]
